project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - spatial_auditing.qmd


website:
  title: "Spatial Auditing Manchester"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: spatial_auditing.qmd
        text: Spatial Auditing method
      - href: OUT/MAP/manchester_scores.html
        text: Manchester scores map
      - href: OUT/TAB/manchester_lsoa_table.html
        text: Manchester scores table
      - href: OUT/MAP/manchester_population.html
        text: Manchester population map

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
